# stages:
#   - pages
pages:
  script:
    - mkdir public
    - cp index.html public
    - cp -r audio public
    - cp -r credits public
    - cp -r img public
    - cp script.js public
    - cp style.css public
    - cp credits.json public
    - cp credits.rawiconurl.json public
  artifacts:
    paths:
      - public
  # tags:
  #   - shell
