# stages:
#   - pages
pages:
  script:
    #    - mkdir public
    #    - cp index.html public
    #    - cp -r audio public
    #    - cp -r credits public
    #    - cp -r img public
    #    - cp script.js public
    #    - cp style.css public
    #    - cp credits.json public
    #    - cp credits.rawiconurl.json public
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  environment: production
  # tags:
  #   - shell
